#!/usr/bin/env python3
"""Adopt the shared + lens super metrics this estate references across postures - step 2 of the recipe.

Reads the portable source (shared/supermetrics.yaml: names, formulas, one cross-reference by key),
upserts each super metric by NAME on your instance (id-preserving update when the name is live,
create otherwise), and emits `supermetrics.shared.yaml` - the instance RECORD whose minted ids
build.py seeds its formulas from and the view generators read.

It then regenerates the one lens view the scorecard's reclaim-evidence panel renders - the
rightsizing oversized-candidates view - from its template, substituting YOUR minted super-metric
ids into the column stat keys, and packages it as a one-click `Views > Manage > Import` bundle.
A view's columns read super metrics by id, and ids mint per instance: regeneration is what makes
the shipped view light up on your estate instead of pointing at another instance's ids.

Execute-by-default like its sibling build.py (--dry-run to preview). Idempotent: re-runs reuse
every already-live name.

Usage (from frameworks/wtpc/):
  python adopt_shared.py [--dry-run]
"""
from __future__ import annotations

import os
import re
import sys
import zipfile

import yaml
from lib._client import ops_client
from lib._sm import existing_supermetrics, upsert_supermetric

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "shared", "supermetrics.yaml")
RECORD = os.path.join(HERE, "supermetrics.shared.yaml")
VIEW_TEMPLATE = os.path.join(HERE, "shared", "oversized-candidates.view.template.xml")
VIEW_OUT = os.path.join(HERE, "content", "rightsizing-oversized-candidates.view.xml")
BUNDLE_OUT = os.path.join(HERE, "content", "wtpc-views-lens-oversized.import.zip")
ZIP_TS = (1980, 1, 1, 0, 0, 0)   # fixed -> reproducible zip bytes (matches build_view_bundles.py)

_REF = re.compile(r"\{SM:([A-Z_]+)\}")


def subst(text: str, ids: dict[str, str]) -> str:
    return _REF.sub(lambda m: ids[m.group(1)], text)


def main() -> int:
    dry = "--dry-run" in sys.argv
    defs = yaml.safe_load(open(SOURCE, encoding="utf-8"))["supermetrics"]
    with ops_client() as c:
        existing = existing_supermetrics(c)
        ids: dict[str, str] = {}
        rows = []
        posted = reused = 0
        for d in defs:
            formula = subst(d["formula"], ids)   # source order is dependency order
            if _REF.search(formula):
                sys.exit(f"unresolved reference in {d['key']}: {formula}")
            sid, action = upsert_supermetric(
                c, name=d["name"], formula=formula, description=d["description"].strip(),
                existing=existing, dry=dry, dry_id=f"DRY-{d['key']}")
            posted += action == "posted"
            reused += action == "reused"
            ids[d["key"]] = sid
            rows.append((d, sid, formula))
        print(f"shared/lens SMs: posted={posted} reused={reused} total={len(rows)}"
              + ("  [DRY-RUN]" if dry else ""))
        if dry:
            print("dry-run is side-effect-free: no record, no view regeneration")
            return 0

        # the instance record (the same shape build.py emits per posture: key/name/id/applies_to)
        lines = [
            "# Shared + lens super metrics - INSTANCE record (GENERATED by adopt_shared.py from",
            "# shared/supermetrics.yaml - do not hand-edit). Ids are this instance's minted ids, an",
            "# output record, not the portable key; rebuild on any instance with adopt_shared.py.",
            "", "supermetrics:"]
        for d, sid, _f in rows:
            lines += [f"  - key: {d['key']}", f"    name: \"{d['name']}\"", f"    id: {sid}",
                      f"    applies_to: [{', '.join(d['applies_to'])}]"]
        open(RECORD, "w", encoding="utf-8").write("\n".join(lines) + "\n")
        print(f"emitted {os.path.basename(RECORD)} ({len(rows)} SMs)")

        # regenerate the lens view with THIS instance's ids + package the one-view import bundle
        xml = subst(open(VIEW_TEMPLATE, encoding="utf-8").read(), ids)
        os.makedirs(os.path.dirname(VIEW_OUT), exist_ok=True)
        open(VIEW_OUT, "w", encoding="utf-8").write(xml)
        with zipfile.ZipFile(BUNDLE_OUT, "w", zipfile.ZIP_DEFLATED) as z:
            z.writestr(zipfile.ZipInfo("content.xml", ZIP_TS), xml)
        print(f"regenerated {os.path.basename(VIEW_OUT)} + {os.path.basename(BUNDLE_OUT)} "
              "(import via Views > Manage > Import, before the posture dashboards)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
